package com.github.sergeisolodkov.voipadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettingAllPropertiesEquals(Setting expected, Setting actual) {
        assertSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettingAllUpdatablePropertiesEquals(Setting expected, Setting actual) {
        assertSettingUpdatableFieldsEquals(expected, actual);
        assertSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettingAutoGeneratedPropertiesEquals(Setting expected, Setting actual) {
        assertThat(expected)
            .as("Verify Setting auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettingUpdatableFieldsEquals(Setting expected, Setting actual) {
        assertThat(expected)
            .as("Verify Setting relevant properties")
            .satisfies(e -> assertThat(e.getTextValue()).as("check textValue").isEqualTo(actual.getTextValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettingUpdatableRelationshipsEquals(Setting expected, Setting actual) {
        assertThat(expected)
            .as("Verify Setting relationships")
            .satisfies(e -> assertThat(e.getOption()).as("check option").isEqualTo(actual.getOption()))
            .satisfies(e -> assertThat(e.getSelectedValues()).as("check selectedValues").isEqualTo(actual.getSelectedValues()))
            .satisfies(e -> assertThat(e.getDevice()).as("check device").isEqualTo(actual.getDevice()));
    }
}
