package com.github.sergeisolodkov.voipadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VendorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAllPropertiesEquals(Vendor expected, Vendor actual) {
        assertVendorAutoGeneratedPropertiesEquals(expected, actual);
        assertVendorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAllUpdatablePropertiesEquals(Vendor expected, Vendor actual) {
        assertVendorUpdatableFieldsEquals(expected, actual);
        assertVendorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAutoGeneratedPropertiesEquals(Vendor expected, Vendor actual) {
        assertThat(expected)
            .as("Verify Vendor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorUpdatableFieldsEquals(Vendor expected, Vendor actual) {
        assertThat(expected)
            .as("Verify Vendor relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorUpdatableRelationshipsEquals(Vendor expected, Vendor actual) {
        assertThat(expected)
            .as("Verify Vendor relationships")
            .satisfies(e -> assertThat(e.getOptions()).as("check options").isEqualTo(actual.getOptions()));
    }
}
